name: Publish Docker image

on:
  push:
    branches: [ main ]

jobs:
  push_to_registry_CO:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./environment
          file: ./environment/Dockerfile
          push: true
          tags: ghcr.io/allenneuraldynamics/aind-ophys-extraction-suite2p-docker:latest
  push_to_registry_local:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./environment
          file: ./environment/Dockerfile_local
          push: true
          tags: ghcr.io/allenneuraldynamics/aind-ophys-extraction-suite2p-docker-local:latest